# Generated by Django 6.0.7 on 2026-07-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0002_alter_barangay_options_barangay_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_covered', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('activity_location', models.CharField(max_length=255)),
                ('participants', models.PositiveIntegerField()),
                ('waste_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waste_type', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Returned', 'Returned')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barangays.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weekly_reports/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.weeklyreport')),
            ],
        ),
    ]
