# Generated by Django 6.0.7 on 2026-07-09 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('waterway', models.CharField(max_length=200)),
                ('length_covered', models.DecimalField(decimal_places=2, max_digits=8)),
                ('waste_collected', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disposal_method', models.TextField()),
                ('remarks', models.TextField(blank=True)),
                ('prepared_by', models.CharField(max_length=100)),
                ('certified_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barangays.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('before', 'Before'), ('during', 'During'), ('after', 'After'), ('waste', 'Collected Waste'), ('group', 'Group Photo')], max_length=20)),
                ('image', models.ImageField(upload_to='reports/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.weeklyreport')),
            ],
        ),
    ]
