# Generated by Django 6.0.7 on 2026-07-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='menro_remarks',
            field=models.TextField(blank=True),
        ),
    ]
