# Generated by Django 6.0.7 on 2026-07-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_weeklyreport_menro_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportphoto',
            name='category',
            field=models.CharField(choices=[('Before', 'Before'), ('During', 'During'), ('After', 'After'), ('Collected Waste', 'Collected Waste'), ('Group Photo', 'Group Photo'), ('Attendance', 'Attendance')], default='Before', max_length=30),
            preserve_default=False,
        ),
    ]
