# Generated by Django 6.0.7 on 2026-07-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportphoto_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='disposal_method',
            field=models.TextField(blank=True, verbose_name='Method of Disposal'),
        ),
    ]
