# Generated by Django 6.0.7 on 2026-07-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_weeklyreport_disposal_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='waste_collected',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='waste_type',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='biodegradable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='potential',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='recyclable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='residual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
