# Generated by Django 6.0.7 on 2026-07-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_weeklyreport_waste_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='length_covered',
            field=models.PositiveIntegerField(default=0, help_text='Length covered in meters'),
        ),
    ]
