# Generated by Django 6.0.7 on 2026-07-18 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0005_remove_barangay_punong_barangay'),
        ('reports', '0006_weeklyreport_length_covered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DCFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('week_covered', models.CharField(blank=True, max_length=100)),
                ('has_bswmc', models.BooleanField(default=False)),
                ('bswmc_members', models.PositiveIntegerField(default=0)),
                ('bswmc_meetings', models.PositiveIntegerField(default=0)),
                ('has_eo', models.BooleanField(default=False)),
                ('has_bswm_plan', models.BooleanField(default=False)),
                ('has_swm_program', models.BooleanField(default=False)),
                ('swm_program_description', models.TextField(blank=True)),
                ('cleanup_drives', models.PositiveIntegerField(default=0)),
                ('cleanup_participants', models.PositiveIntegerField(default=0)),
                ('cleanup_area', models.CharField(blank=True, max_length=255)),
                ('segregation_implemented', models.BooleanField(default=False)),
                ('collection_schedule', models.CharField(blank=True, max_length=255)),
                ('households_served', models.PositiveIntegerField(default=0)),
                ('households_compliant', models.PositiveIntegerField(default=0)),
                ('has_mrf', models.BooleanField(default=False)),
                ('mrf_location', models.CharField(blank=True, max_length=255)),
                ('mrf_operational', models.BooleanField(default=False)),
                ('mrf_workers', models.PositiveIntegerField(default=0)),
                ('biodegradable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recyclable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('residual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diverted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_ordinance', models.BooleanField(default=False)),
                ('violations_recorded', models.PositiveIntegerField(default=0)),
                ('penalties_imposed', models.PositiveIntegerField(default=0)),
                ('iec_activities', models.PositiveIntegerField(default=0)),
                ('iec_participants', models.PositiveIntegerField(default=0)),
                ('best_practices', models.TextField(blank=True)),
                ('prepared_by', models.CharField(blank=True, max_length=150)),
                ('certified_by', models.CharField(blank=True, max_length=150)),
                ('menro_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Returned', 'Returned')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barangays.barangay')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
