# Generated by Django 6.0.7 on 2026-07-25 05:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_dcfreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='weekly_reports'),
        ),
    ]
