# Generated by Django 6.0.7 on 2026-07-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_reportphoto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcfreport',
            name='diverted',
        ),
        migrations.AlterField(
            model_name='dcfreport',
            name='residual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Residual w/ Potential (kg)'),
        ),
    ]
