# Generated by Django 6.0.7 on 2026-07-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_dcfreport_approved_at_dcfreport_returned_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='biodegradable',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='potential',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='recyclable',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='residual',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='barangay_officials',
            field=models.PositiveIntegerField(default=0, verbose_name='No. of Barangay Officials'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='cso_members',
            field=models.PositiveIntegerField(default=0, verbose_name='No. of Civil Society Organization (CSO)'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='sk_members',
            field=models.PositiveIntegerField(default=0, verbose_name='No. of Sangguniang Kabataan'),
        ),
    ]
