# Generated by Django 6.0.7 on 2026-07-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_weeklyreport_biodegradable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='participants',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
