# Generated by Django 6.0.7 on 2026-08-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_weeklyreport_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='biodegradable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Biodegradable Waste (kg)'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='recyclable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Recyclable Waste (kg)'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='residual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Residual Waste (kg)'),
        ),
    ]
