# Generated by Django 6.0.7 on 2026-08-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_weeklyreport_biodegradable_weeklyreport_recyclable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='volume_of_waste',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total volume of waste collected (kg)', max_digits=10),
        ),
    ]
