# Generated by Django 6.0.7 on 2026-08-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_weeklyreport_volume_of_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcfreport',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='generated_reports/'),
        ),
    ]
