# Generated by Django 6.0.7 on 2026-08-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_dcfreport_generated_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcfreport',
            name='generated_pdf',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='generated_reports/'),
        ),
    ]
