# Generated by Django 6.0.7 on 2026-07-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('municipality', models.CharField(default='Obando', max_length=100)),
                ('punong_barangay', models.CharField(max_length=100)),
                ('environment_chair', models.CharField(max_length=100)),
            ],
        ),
    ]
