# Generated by Django 6.0.7 on 2026-07-09 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangay',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='barangay',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='barangay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barangay',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
