# Generated by Django 6.0.7 on 2026-07-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0002_alter_barangay_options_barangay_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='barangay_logos/'),
        ),
    ]
