# Generated by Django 6.0.7 on 2026-07-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0003_barangay_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='barangay_captain',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='barangay',
            name='committee_chair',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
