# Generated by Django 6.0.7 on 2026-07-11 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0004_barangay_barangay_captain_barangay_committee_chair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='punong_barangay',
        ),
    ]
