# Generated by Django 6.0.7 on 2026-07-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0005_remove_barangay_punong_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='committee_chair',
            field=models.CharField(blank=True, max_length=150, verbose_name='Environment Committee Chair'),
        ),
    ]
