# Generated by Django 6.0.7 on 2026-08-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0006_alter_barangay_committee_chair'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='captain_signature',
            field=models.CharField(blank=True, help_text='Example: captain_catanghalan.png', max_length=255),
        ),
        migrations.AddField(
            model_name='barangay',
            name='committee_signature',
            field=models.CharField(blank=True, help_text='Example: committee_catanghalan.png', max_length=255),
        ),
    ]
